### ISSUE TITLE
Custom extent class type has incorrect interval field type

### ISSUE THREAD

**Issue by ernstdevreede** [KNMI/edr-pydantic#8]
The `interval` field in the Custom class (in extent.py) has the type     `interval: List[str]`.
According to the standard this should be: `interval: List[List[str]]` or even better `interval: List[List[str|float]]`

See: https://docs.ogc.org/is/19-086r6/19-086r6.html#_a2113fbe-7d9d-4295-bdfa-25b9cc89fa03 where the schema states:
```
type: object
required:
    - id
    - interval
    - reference
properties:
    id:
        type: string
    interval:
        type: array
        minItems: 1
        items:
            type: array
            minItems: 2
            items:
                anyOf:
                    - type: string
                    - type: number
            nullable: true
...

```
